/* DEFINIR TDA PARA SCENE */

/* ESCENARIOS: */
/* 3 ESCENARIOS DE 5X10 */

scene(5,10,2).
scene(5,10,4).
scene(5,10,5).

/* 2 ESCENARIOS DE 10X12 */

scene(10,12,4).
scene(10,12,6).

/* 1 ESCENARIO DE 20X20 */

scene(20,20,2).

/* IMPLEMENTAR FUNCION CREATE SCENE */

   /* D AFECTA LA CANTIDAD DE PERSONAJES DEL EQUIPO
      DEL JUGADOR Y LA POSICIÓN DE LOS OBSTACULOS */

   /* SEMILLA USADA PARA GENERAR VARIABLES SEUDO ALEATORIAS:
      -POSICION DE OBSTACULOS */

   /* CHEQUEAR SI ES POSIBLE DISPONER A TODOS LOS
      ENEMIGOS EN DICHO ESPACIO */

   /* DE NO SER POSIBLE, RETORNAR NULO */

/* CHECK SCENE */

   /* RECIBE TDA SCENE */

   /* CONSULTAR SI UN ESCENARIO ES VALIDO */

      /* DIMENSIONES VALIDAS */

      /* ENTIDADES VALIDAMENTE UBICADAS,
         SIN SUPERPOSICIÓN ENTRE ELLOS */ 

/* MOVE MEMBER */ 
 
   /* CONSULTA SI ES POSIBLE MOVER UN PERSONAJE
      DE CIERTO EQUIPO EN CIERTA DIRECCION */

   /* VERIFICAR EL DESPLAZAMIENTO, IZQUIERDA O DERECHA */

   /* ENTREGA RESULTADO DE MOVIMIENTO POR MEDIO DE VARIABLE SCENEOUT */

/* SHOOT */

   /* CONSULTA EL VALOR QUE DEBE TOMAR SCENEOUT
      PARA CORRESPONDER AL ESCENARIO TRAS UN DISPARO */

/* UPDATE SCENE */

   /* CONSULTA EL VALOR QUE DEBE TOMAR SCENEOUT
      PARA SER EL ESTADO DEL ESCENARIO AVANZADO UN TIC */

/* SCENE TO STRING */

   /* CONSULTA EL VALOR QUE DEBE TOMAR SCENESTR PARA QUE EL
      PREDICADO, A PARTIR DE SCENE, SEA VERDADERO */

   /* NO USAR PREDICADOS WRITE Y DISPLAY DENTRO DE SCENE TO STRING
      YA QUE LA VARIABLE SCENESTR DEBE SER UN STRING QUE LUEGO SEA
      USADO POR EL PREDICADO WRITE O DISPLAY */

   /* EL STRING DEBE SER IMPRESO POR DICHAS FUNCIONES */
